apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-pvp
spec:
    capacity:
      storage: 2Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /home/data
      server: 192.168.199.222
