kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: webhook-dingtalk 
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webhook-dingtalk
    spec:
      containers:
        - name: webhook-dingtalk
          image: timonwong/prometheus-webhook-dingtalk
          ports:
          - containerPort: 8060
            name: port
          #command: [ "/bin/sh", "-c", "sleep 20000" ] 
          args:
          - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=abd2d8f02652277d5765da4e21f171bd87278c830d277d54699630db2182a17d
      restartPolicy: Always
---
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-dingtalk
  namespace: kube-system
  labels:
    name: webhook-dingtalk
spec:
  ports:
    - name: port
      port: 8060
      targetPort: 8060
  selector:
    app: webhook-dingtalk
